# Generated by Django 5.2.17 on 2026-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_paise',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
