# Generated by Django 5.2.17 on 2026-09-29 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=80)),
                ('service_radius_km', models.PositiveIntegerField(default=25)),
                ('is_verified', models.BooleanField(default=False)),
                ('razorpay_linked_account_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD_TRUCK', 'Food Truck'), ('AV_CREW', 'AV Setup Crew'), ('SECURITY', 'Security Team'), ('DECOR', 'Decor')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price_paise', models.PositiveBigIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(default=240)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vendors.vendorprofile')),
            ],
        ),
    ]
