# Generated by Django 5.2.17 on 2026-10-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancel_reason_booking_cancelled_at_and_more'),
        ('payments', '0002_payment_refund_id_payment_refunded_paise'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMPLETION', 'Completed booking'), ('CANCELLATION', 'Late-cancellation compensation')], max_length=15)),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('platform_fee_paise', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RELEASED', 'Released'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('release_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='mock', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('dispute_reason', models.CharField(blank=True, max_length=255)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='bookings.booking')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'release_at'], name='payments_pa_status_2fdb29_idx')],
            },
        ),
    ]
